### ISSUE TITLE
inverted splines do not work with MonotoneCubicSpline

### ISSUE THREAD

**Issue by Wobblyyyy** [Wobblyyyy/Pathfinder2#3]
**Describe the bug**
inverted splines aren't working correctly

**To Reproduce**
1. run the tests in `TestAdvancedSplineTrajectory`

**Expected behavior**
the robot should move to a negative coordinate but it's not doing that - it's going to a positive coordinate instead, which is obviously not what we want lol

```
TestAdvancedSplineTrajectory > testBackwardsLinearSpline() FAILED
    org.opentest4j.AssertionFailedError: Could not assert position! Expected <(-20.0, -20.0, 0.0 deg)> but got <(18.738, 18.738, 0.0 deg)> instead. Distance <54.784271247461874> was greater than maximum distance of <2.0>! ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at me.wobblyyyy.pathfinder2.GenericTrajectoryTester.assertPositionIs(GenericTrajectoryTester.java:62)
        at me.wobblyyyy.pathfinder2.trajectory.spline.TestAdvancedSplineTrajectory.testSplineTo(TestAdvancedSplineTrajectory.java:25)
        at me.wobblyyyy.pathfinder2.trajectory.spline.TestAdvancedSplineTrajectory.testBackwardsLinearSpline(TestAdvancedSplineTrajectory.java:36)

TestAdvancedSplineTrajectory > testBackwardsTurningLinearSpline() FAILED
    org.opentest4j.AssertionFailedError: Could not assert position! Expected <(-20.0, -20.0, 90.0 deg)> but got <(20.153, 20.153, 85.182 deg)> instead. Distance <56.78427124746189> was greater than maximum distance of <2.0>! ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at me.wobblyyyy.pathfinder2.GenericTrajectoryTester.assertPositionIs(GenericTrajectoryTester.java:62)
        at me.wobblyyyy.pathfinder2.trajectory.spline.TestAdvancedSplineTrajectory.testSplineTo(TestAdvancedSplineTrajectory.java:25)
        at me.wobblyyyy.pathfinder2.trajectory.spline.TestAdvancedSplineTrajectory.testBackwardsTurningLinearSpline(TestAdvancedSplineTrajectory.java:48)
```

**Comment by Wobblyyyy** [comment]
fixed as of commit [1403183](https://github.com/Wobblyyyy/Pathfinder2/commit/1403183352d67c03aaac0fd48210cd2254e344e0). there was a missing `break` statement in a switch that was causing the wrong type of spline to be instantiated.
